### ISSUE TITLE
Arboles sanos pero con daño

### ISSUE THREAD

**Issue by AliciaMstt** [AliciaMstt/monitoreo-oyameles#1]
Hay muchos árboles, principalmente de brigadistas F y L que dicen healthy + algún daño, lo cual evidentemente es un error. ¿Se equivocó al poner sano y en realidad están dañados o al revez? Preguntarle a brigadistas F y L y/o revisar fotos. 

Por lo pronto el script de limpieza omite estos datos.

```{r}
# check if there are any trees with healthy + other. If this is the case, there should be an " " after healthy
muestreo[grep("healthy ", muestreo$tree_health), c("plot", "tree_id")]

     plot tree_id
44     19     F69
93     41    L101
517    10     F52
520    10     F54
726    19     F71
735    19     F73
818    25     F77
885    23     L65
887    23     L66
893    26     L73
1033   28     F86
1079   29     F94
1109   29     L81
1111   32     F98
1112   32     F99
1119   32    F109
1299   41    F113
1326   41    F116
1328   41    F117
1336   41    F125
1337   41    F126
1405   32    F105
1406   25     F78
1409   32    F107
1443   25     F81
1445   32    F104
1541   46    B136
1542   46    B135
1555   35     G13
1637   40    I129
1638   40    I130
1640   41     L99
1658   48    F133
1660   48    F135
1662   48    F137
1669   39    B123
1682   10     F55
1683   10     F56
1685   28     F85
1688   30     G83
```

**Comment by VeroIarrachtai** [comment]
Se revisaron los datos comparando con las fotos tomadas por cada brigadista y se corrigieron de la siguiente manera:
```
    plot tree_id condition
44     19     F69 ozono/sequia
93     41    L101 sana
517    10     F52 sequia/otros
520    10     F54 otros
726    19     F71 ozono/sequia
735    19     F73 ozono/sequa
818    25     F77 sequia
885    23     L65 otros
887    23     L66 otros
893    26     L73 otros
1033   28     F86 sequia
1079   29     F94 otros
1109   29     L81 otros
1111   32     F98 otros
1112   32     F99 otros
1119   32    F109 ozono
1299   41    F113 sequia
1326   41    F116 ozono
1328   41    F117 otros
1336   41    F125 sana
1337   41    F126 otros
1405   32    F105 otros
1406   25     F78  otros
1409   32    F107 sana
1443   25     F81 otros
1445   32    F104 sana
1541   46    B136 ozono
1542   46    B135 otros
1555   35     G13 sana (era G131, también se corrigió)
1637   40    I129 ozono/sequia
1638   40    I130 ozono/sequia
1640   41     L99 ozono/sequia/otros
1658   48    F133 otros
1660   48    F135 otros
1662   48    F137 otros
1669   39    B123 otros
1682   10     F55 otros
1683   10     F56 otros
1685   28     F85 sana
1688   30     G83 otros
```

G13 se cambio a G131 debido a que la fotografía, su parcela y sus coordenadas indicaban que en realidad este individuo correspondia a la clave G131.

Falta que cada dato sea aceptado o rechazado por quien le corresponda validar esos datos (Alicia, Vale o Vero).

**Comment by AliciaMstt** [comment]
Actualicé los datos en el github y corrí el script de limpieza de nuevo. Commit 04fba608d7c27a61fc4d81290dbf2c014899b3cd

Parece faltan estos:

```
791 | 32 | F104
1766 | 29 | F94
```

**Comment by VeroIarrachtai** [comment]
791 | 32 | F104    queda como sana 
1766 | 29 | F94    queda como sequía y otros

Queda pendiente validar los datos finales

**Comment by AliciaMstt** [comment]
No entendí lo de que "queda pendiente validaro los datos finales" ¿a qué te refieres?

**Comment by AliciaMstt** [comment]
Me sigue apareciendo este individuo sano pero con daño:
plot tree_id
 39 | B121

**Comment by VeroIarrachtai** [comment]
Con   el comentario de  "queda pendiente validaro los datos finales"  me refería a que faltaba la validación de los datos.
Una vez validados los datos a partir de la revisión fotográfica en conjunto o a fondo los datos se determinaron como:


 plot tree_id condition
44     19     F69 ozono/hongos/sequia
93     41    L101 sana
517    10     F52 sequia/otros
520    10     F54 hongos/otros
726    19     F71 ozono/sequia/otros
735    19     F73 ozono/sequía/otros
818    25     F77 sequia/otros
885    23     L65 otros
887    23     L66 otros
893    26     L73 otros
1033   28     F86 sequia/otros
1079   29     F94 sequía/otros
1109   29     L81 otros
1111   32     F98 otros
1112   32     F99 otros
1119   32    F109 ozono
1299   41    F113 sequia
1326   41    F116 ozono
1328   41    F117 otros
1336   41    F125 sana
1337   41    F126 otros
1405   32    F105 otros
1406   25     F78  otros
1409   32    F107 sana
1443   25     F81 otros
1445   32    F104 sana
1541   46    B136 ozono/otros
1542   46    B135 otros
1555   35     G13 sana hongos/otros (era G131, también se corrigió)
1637   40    I129 ozono/sequia
1638   40    I130 ozono/sequia/otros
1640   41     L99 ozono/otros
1658   48    F133 otros
1660   48    F135 sequía/otros
1662   48    F137 otros
1669   39    B123 otros
1682   10     F55 otros
1683   10     F56 otros
1685   28     F85 sana
1688   30     G83 otros

**Comment by VeroIarrachtai** [comment]
Con el comentario de "queda pendiente validar los datos finales" me refería a que faltaba la validación profunda a partir del registro fotográfico de los datos.
Una vez validados los datos a partir de la revisión fotográfica a fondo de los datos se validaron como:

plot tree_id condition
44 19 F69 ozono/hongos/sequia
93 41 L101 sana
517 10 F52 sequia/otros
520 10 F54 hongos/otros
726 19 F71 ozono/sequia/otros
735 19 F73 ozono/sequía/otros
818 25 F77 sequia/otros
885 23 L65 otros
887 23 L66 otros
893 26 L73 otros
1033 28 F86 sequia/otros
1079 29 F94 sequía/otros
1109 29 L81 otros
1111 32 F98 otros
1112 32 F99 otros
1119 32 F109 ozono
1299 41 F113 sequia
1326 41 F116 ozono
1328 41 F117 otros
1336 41 F125 sana
1337 41 F126 otros
1405 32 F105 otros
1406 25 F78 otros
1409 32 F107 sana
1443 25 F81 otros
1445 32 F104 sana
1541 46 B136 ozono/otros
1542 46 B135 otros
1555 35 G13 sana hongos/otros (era G131, también se corrigió)
1637 40 I129 ozono/sequia
1638 40 I130 ozono/sequia/otros
1640 41 L99 ozono/otros
1658 48 F133 otros
1660 48 F135 sequía/otros
1662 48 F137 otros
1669 39 B123 otros
1682 10 F55 otros
1683 10 F56 otros
1685 28 F85 sana
1688 30 G83 otros
