### ISSUE TITLE
arboles en parcela > 48

### ISSUE THREAD

**Issue by AliciaMstt** [AliciaMstt/monitoreo-oyameles#2]
Solo muestreamos 48 parcelas, sin embargo hay árboles que fueron anotados en una parcela mayor. Ver si se puede corregir el typo. Por lo pronto el script de limpieza omite estas muestras.

```{r}
> filter(muestreo, plot > 48) %>% select(plot, person_key, life_condition, tree_id)
  plot person_key life_condition tree_id
1   54                      dead      NA
2  118          B          alive    B118
3   82          E          alive     E82
```

**Comment by VeroIarrachtai** [comment]
Considerando que la muestra tiene una coordenada (19.2904043 -99.3064081) cercana a la ubicación de la parcela 10 (19.2904147 -99.3062129) podemos asignarle esa(parcela 10) en lugar de la 54.

```
    plot person_key life_condition tree_id
1   54                      dead      NA
```
Considerando que individuos con los números 114-124 del brigadista B fueron colectados en la parcela 29 podemos asignar esta parcela (29) al individuo 118.

```
   plot person_key life_condition tree_id
2  118          B          alive    B118
```
Considerando la coordenada del individuo 82 (19.3021058 -99.2976432) su ubicación es dentro de la parcela 28 (19.3020744 -99.2977154), por lo tanto podemos editar este 82 por un 28.

```
     plot person_key life_condition tree_id
3   82          E          alive     E82
```

**Comment by AliciaMstt** [comment]
Vero hace los cambios directos en el kobo.

**Comment by VeroIarrachtai** [comment]
LIsto, ya se realizaron los cambios ;)
