### ISSUE TITLE
Árboles con más de una categoría de daño

### ISSUE THREAD

**Issue by AliciaMstt** [AliciaMstt/monitoreo-oyameles#3]
La variable de porcentaje de daño debería de tener una sola respuesta, pero hay 5 árboles donde por error se pusieron dos categorías a la hora del muestreo. 

```
     plot tree_id ozone_damage_percentage
601    38    D138     10 to 40% 50 to 70%
608    38    D145     40 to 50% 50 to 70%
875    46    H174     10 to 40% 50 to 70%
903    35    G116 less than 10% 10 to 40%
1124   33     L86 less than 10% 10 to 40%
```

Hay que revisar las fotografías para ver si podemos determinar la categoría correcta. Por lo pronto el script borra los datos que tengan más de una categoría.

**Comment by VeroIarrachtai** [comment]
Se revisaron las fotos y los datos quedaron de la siguiente manera:

     plot tree_id ozone_damage_percentage
601    38    D138     50 to 70%
608    38    D145     50 to 70% 
875    46    H174     10 to 40%
903    35    G116 less than 10% 
1124   33     L86 less than 10%

**Comment by AliciaMstt** [comment]
Antes no aparecía en la lista (o no sé si copié mal) pero ahorita que hice la revisón con los datos que validaste aparece este:

```
plot tree_id ozono_damage_percentage
11 | E42 | 40 to 50% more than 70%
```

**Comment by VeroIarrachtai** [comment]
Dato correjido de acuerdo al registro fotográfico.
se determino como 40 to 50%

**Comment by VeroIarrachtai** [comment]
Dato correjido de acuerdo al registro fotográfico.
se determino como 40 to 50%
